In [37]:
import sys
import numpy as np
import thinkstats2
from collections import defaultdict
dct_file='D:/data science/classes/DSC530 Exploratory_Data_Analysis/thinkstats/ThinkStats2-master/code/2002FemResp.dct'
dat_file='D:/data science/classes/DSC530 Exploratory_Data_Analysis/thinkstats/ThinkStats2-master/code/2002FemResp.dat.gz'

dct_file2='D:/data science/classes/DSC530 Exploratory_Data_Analysis/thinkstats/ThinkStats2-master/code/2002FemPreg.dct'
dat_file2='D:/data science/classes/DSC530 Exploratory_Data_Analysis/thinkstats/ThinkStats2-master/code/2002FemPreg.dat.gz'

nrows=None

#df: respondent DataFrame
   
    
dct = thinkstats2.ReadStataDct(dct_file)
df = dct.ReadFixedWidth(dat_file, compression='gzip', nrows=nrows)

#df2: pregnancy DataFrame

dct2 = thinkstats2.ReadStataDct(dct_file2)
df2 = dct2.ReadFixedWidth(dat_file2, compression='gzip', nrows=nrows)

In [40]:
df.head()

,caseid,rscrinf,rdormres,rostscrn,rscreenhisp,rscreenrace,age_a,age_r,cmbirth,agescrn,...,pubassis_i,basewgt,adj_mod_basewgt,finalwgt,secu_r,sest,cmintvw,cmlstyr,screentime,intvlngth
0,2298,1,5,5,1,5.0,27,27,902,27,...,0,3247.916977,5123.759559,5556.717241,2,18,1234,1222,18:26:36,110.492667
1,5012,1,5,1,5,5.0,42,42,718,42,...,0,2335.279149,2846.799490,4744.191350,2,18,1233,1221,16:30:59,64.294000
2,11586,1,5,1,5,5.0,43,43,708,43,...,0,2335.279149,2846.799490,4744.191350,2,18,1234,1222,18:19:09,75.149167
3,6794,5,5,4,1,5.0,15,15,1042,15,...,0,3783.152221,5071.464231,5923.977368,2,18,1234,1222,15:54:43,28.642833
4,616,1,5,4,1,5.0,20,20,991,20,...,0,5341.329968,6437.335772,7229.128072,2,18,1233,1221,14:19:44,69.502667

In [39]:
df2.head()

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,poverty_i,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,3410.389399,3869.349602,6448.271112,2,9,1231
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,3410.389399,3869.349602,6448.271112,2,9,1231
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231

In [27]:
df.pregnum

0       4
1       1
2       1
3       0
4       0
       ..
7638    1
7639    0
7640    0
7641    0
7642    0
Name: pregnum, Length: 7643, dtype: int64

pregnum is a record that indicates how many times each respondent has been pregnant. 

will count the values and compare to results published in the [codebook](https://www.icpsr.umich.edu/nsfg6/Controller?displayPage=labelDetails&fileCode=FEM&section=R&subSec=7869&srtLabel=606835)

In [36]:
pregnum_values = df.pregnum.value_counts().sort_index()
print(pregnum_values)
count_7_95 = pregnum_values[7:96].sum()
print('count_7_95 :' + str(count_7_95))
print('total :' + str(pregnum_values.sum()))

0     2610
1     1267
2     1432
3     1110
4      611
5      305
6      150
7       80
8       40
9       21
10       9
11       3
12       2
14       2
19       1
Name: pregnum, dtype: int64
count_7_95 :158
total :7643

In [94]:
#Make a map from caseid to list of preg indices.
#df2_map: dict that maps from caseid to list of indices into `df2`

d = defaultdict(list)
for index, caseid in df2.caseid.iteritems():
    d[caseid].append(index)
df2_map = d

In [95]:
##Validate pregnum in the respondent file
invalid=0
valid = 0
for index, pregnum in df.pregnum.items():
    caseid = df.caseid[index]
    indices = df2_map[caseid]

        # check that pregnum from the respondent file equals
        # the number of records in the pregnancy file
    if len(indices) != pregnum:
      
        invalid=invalid+1

    else: 
        valid = valid + 1
        
print('invalid count :' + str(invalid))
print('valid count   :' + str(valid))
#return True

invalid count :0
valid count   :7643

cross validation above confirm that number of pregnacy by caseid matches between respendent and pregnancy files